homeassistant:
  name: Casa
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 4.2
  unit_system: metric
  time_zone: Europe/Lisbon
  customize: !include customize.yaml

ffmpeg:
 ffmpeg_bin: /usr/bin/ffmpeg

map:
zone: !include zones.yaml

history:
logbook:
recorder:
  purge_keep_days: 30
  db_url: !secret db_connectionString

frontend:
 javascript_version: latest
 themes: !include_dir_merge_named themes/
 extra_html_url:
   - /local/custom_ui/state-card-mini-media-player.html
   - /local/custom_ui/state-card-guestwifi.html
   - /local/custom_ui/state-card-floorplan.html
 extra_html_url_es5:
   - /local/custom_ui/state-card-mini-media-player_es5.html
   - /local/custom_ui/state-card-guestwifi.html
   - /local/custom_ui/state-card-floorplan.html
   
updater:
 include_used_components: true
 
http:
 api_password: !secret http_password
 ssl_certificate: !secret http_ssl_certificate
 ssl_key: !secret http_ssl_key
 base_url: !secret http_url

google_assistant: !include google_assistant.yaml
 
config:
scene: !include scenes.yaml
mqtt: !include includes/mqtt.yaml
group: !include_dir_merge_named includes/group
automation: !include automations.yaml
script: !include scripts.yaml
sun:
notify: !include includes/notify.yaml
sensor: !include includes/sensor.yaml
light: !include includes/light.yaml
camera: !include includes/camera.yaml
device_tracker: !include includes/device_tracker.yaml
media_player: !include includes/media_player.yaml
input_text: !include includes/input_text.yaml
binary_sensor: !include includes/binary_sensor.yaml
input_boolean: !include includes/input_boolean.yaml